# -*- coding: utf-8 -*-
"""Tarea2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Z4mxbq4GmuS3kXcgF7d0iiNMRJfPI-1
"""

import matplotlib.pyplot as plt
from sklearn.cluster import (
    AgglomerativeClustering,
    KMeans
)
from scipy.cluster.hierarchy import dendrogram
import seaborn as sns
import matplotlib.colors as mcolors
import pandas as pd
import numpy as np
from typing import Literal
import networkx as nx
from scipy.cluster.hierarchy import (
    fcluster,
    linkage
)
from scipy.spatial.distance import squareform
from sklearn.metrics import (
    silhouette_score,
    confusion_matrix
)
from fcmeans import FCM
from sklearn.decomposition import (
    KernelPCA,
    PCA
)
from IPython.display import display
from sklearn.datasets import (
    make_moons,
    make_circles
)
from mpl_toolkits.mplot3d import Axes3D

"""## Problema 2

### Creamos cluster
"""

# Parámetros del grafo
N = 100
prob_in = 0.3  # Probabilidad dentro de comunidades
prob_out = 0.03  # Probabilidad entre comunidades
n_comunidades = 3 # Número de comunidades

# Asignamos comunidades a nodos
np.random.seed(42)
etiquetas_comunidad = np.random.randint(1, n_comunidades+1, N)

# Inicializar grafo
G = nx.Graph()
G.add_nodes_from(range(N))

# Agregamos conexiones en base a las probabilidades definidas.
contador_aristas = 0
for i in range(N):
    for j in range(i + 1, N):
        if etiquetas_comunidad[i] == etiquetas_comunidad[j]:  # Misma comunidad
            if np.random.rand() < prob_in:
                G.add_edge(i, j)
                contador_aristas += 1
        else:  # Diferentes comunidades
            if np.random.rand() < prob_out:
                G.add_edge(i, j)
                contador_aristas += 1

print("M =",contador_aristas) # Número M de aristas

# Dibujar el grafo con colores por comunidad
plt.figure(figsize=(6,6))
colors = ["C"+str(etiquetas_comunidad[i]+1) for i in range(N)]
nx.draw(G, node_color=colors, with_labels=True, node_size=300, edge_color="gray")
plt.savefig("p2_grafo.pdf", format="pdf", bbox_inches="tight")

"""### Matriz de disimilaridades"""

# Matriz de adyacencia
A = nx.to_numpy_array(G)

# Calcular la matriz de disimilaridades basada en caminos mínimos (Dijkstra)
def matriz_disimilaridades(G):
    N = len(G.nodes)
    D = np.full((N, N), np.inf) # Inicializamos
    np.fill_diagonal(D, 0)

    # Calcular distancias más cortas desde cada nodo
    for i in range(N):
        lengths = nx.single_source_shortest_path_length(G, i)
        for j, dist in lengths.items():
            D[i, j] = dist

    max_finite = np.max(D[D < np.inf])  # Máxima distancia válida
    D[D == np.inf] = max_finite * 1.5  # Valor máximo imputado
    return D

D = matriz_disimilaridades(G)

"""### Clustering Jerárquico"""

def jerarquico_grafos(D, enlace : Literal["single","complete","average"], n_clusters):
    D_condensada = squareform(D)
    matriz_enlace = linkage(D_condensada, method=enlace)
    clusters = fcluster(matriz_enlace, t=n_clusters, criterion='maxclust')
    return clusters

"""### Evaluar

Coeficiente de siluetas
"""

# Evaluamos con los 3 enlaces
enlaces = ["single","average","complete"]
n_clusters=3

for enlace in enlaces:
    clusters = jerarquico_grafos(D,enlace=enlace, n_clusters=n_clusters)
    try:
        score = silhouette_score(D, clusters, metric="precomputed")
        print(f"CS con enlace {enlace} = {score:.3f}")
    except:
        print(f"Error con {enlace}")

"""Matriz de confusion"""

clusters = jerarquico_grafos(D, enlace="average", n_clusters=n_clusters)

print(clusters)
print(etiquetas_comunidad)

# Traducimos las etiquetas de los clusters calculados a las etiquetas reales
calculado = {1 : 3, 2: 1, 3 : 2}
clusters_traducidos = np.zeros(clusters.shape)
for i in range(len(clusters)):
    clusters_traducidos[i] = calculado[clusters[i]]

cm = confusion_matrix(etiquetas_comunidad, clusters_traducidos)
print(cm)

# Crear el heatmap con seaborn
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=[1,2,3], yticklabels=[1,2,3])
plt.xlabel("Comunidad predicha")
plt.ylabel("Comunidad real")
plt.savefig("p2_cm.pdf", format="pdf", bbox_inches="tight")

precision = np.diag(cm) / np.sum(cm, axis = 0)
recall = np.diag(cm) / np.sum(cm, axis = 1)

for i, (p, r) in enumerate(zip(precision, recall)):
    print(f"Comunidad {i+1}:")
    print(f"Precision = {p:.3f}")
    print(f"Recall = {r:.3f}")
    print("-" * 20)

"""## Problema 3

### Visualizar
"""

X_moon, y_moon = make_moons(n_samples=300, noise=0.1, random_state=42)

df_moon = pd.DataFrame({"x": X_moon[:, 0],
                        "y": X_moon[:, 1],
                        "class": y_moon})


fig, ax = plt.subplots(1,1,figsize=(6,4))

sns.scatterplot(data=df_moon, x="x", y="y", hue="class", ax = ax)
plt.title("Lunas", size=18)
plt.legend(title="Clases")
plt.xlabel("")
plt.ylabel("")
plt.savefig("p3.pdf", format="pdf", bbox_inches="tight")

"""### CJA con lo mejor que me haya funcionado"""

def plot_dendrogram(model, **kwargs):
    # Create linkage matrix and then plot the dendrogram

    # create the counts of samples under each node
    counts = np.zeros(model.children_.shape[0])
    n_samples = len(model.labels_)
    for i, merge in enumerate(model.children_):
        current_count = 0
        for child_idx in merge:
            if child_idx < n_samples:
                current_count += 1  # leaf node
            else:
                current_count += counts[child_idx - n_samples]
        counts[i] = current_count

    linkage_matrix = np.column_stack(
        [model.children_, model.distances_, counts]
    ).astype(float)

    # Plot the corresponding dendrogram
    dendrogram(linkage_matrix, **kwargs)

cja1 = AgglomerativeClustering(linkage="complete", compute_distances=True)
cja1 = cja1.fit(X_moon)


plt.title("Complete Linkage", size=18)
plot_dendrogram(cja1, truncate_mode="level", p=10)
plt.tick_params(axis="x", which="both",
                bottom=False,
                top=False,
                labelbottom=False)
plt.savefig("p3_dcl.pdf", format="pdf", bbox_inches="tight")

cja2 = AgglomerativeClustering(linkage="single", compute_distances=True)
cja2 = cja2.fit(X_moon)

plt.title("Single Linkage", size = 18)

plot_dendrogram(cja2)
plt.tick_params(axis="x", which="both",
                bottom=False,
                top=False,
                labelbottom=False)
plt.savefig("p3_dsl.pdf", format="pdf", bbox_inches="tight")

# En la tarea pasada descubrí que me funcionó bien la distancia euclidiana y el enlace
# tipo complete-linkage, el umbral depende de los datos así que no tomaré el resultado
# de la tarea pasada.
fig, ax = plt.subplots(1, 2, figsize=(9, 3))

labels_cja = cja1.fit_predict(X_moon)
df_moon["labels_cja"] = labels_cja
g1 = sns.scatterplot(data=df_moon, x="x", y="y", hue="labels_cja", ax=ax[0])

# Observamos que, en este caso, funciona mejor el single-linkage.
labels_cja = cja2.fit_predict(X_moon)
df_moon["labels_cja"] = labels_cja
g2 = sns.scatterplot(data=df_moon, x="x", y="y", hue="labels_cja", ax=ax[1])

sns.move_legend(g1, loc="upper right", title="Clases (CL)")
sns.move_legend(g2, loc="upper right", title="Clases (SL)")
for i, letra in zip(list(range(2)), ["a", "b"]):
    ax[i].set_xlabel(f"({letra})", size = 13)
    ax[i].set_ylabel("")

plt.savefig("p3_cja.pdf", format="pdf", bbox_inches="tight")

"""### Fuzzy k-means"""

fcm = FCM(n_clusters=2)
fcm.fit(X_moon)
probs = np.round(fcm.soft_predict(X_moon), 3)
lab = np.matrix(fcm.predict(X_moon)).T

df_moon_ja_cfm = pd.DataFrame(np.concatenate([df_moon, probs, lab], axis=1),
                              columns=list(df_moon.columns)+["p0", "p1", "labels_fcm"])

fig, ax = plt.subplots(1, 3, figsize=(16,16))

g1 = sns.scatterplot(data=df_moon_ja_cfm,
                     x="x",
                     y="y",
                     hue="labels_fcm", ax=ax[0])
g2 = sns.scatterplot(data=df_moon_ja_cfm,
                     x="x",
                     y="y",
                     hue="p0", ax=ax[1])
g3 = sns.scatterplot(data=df_moon_ja_cfm,
                     x="x",
                     y="y",
                     hue="p1", ax=ax[2])



sns.move_legend(g1, loc="upper right", title="Clases")
sns.move_legend(g2, loc="upper right", title="Peso 0")
sns.move_legend(g3, loc="upper right", title="Peso 1")

for i, letra in zip(list(range(3)), ["a", "b", "c"]):
    ax[i].set_xlabel(f"({letra})", size=13)
    ax[i].set_ylabel("")
    ax[i].scatter(x=fcm.centers[:, 0], y=fcm.centers[:, 1],
              s=250, marker="*", color="black")
    ax[i].set_aspect("equal")

plt.savefig("p3_fcm.pdf", format="pdf", bbox_inches="tight")

"""## Problema 4"""

num_points = 500
theta = np.linspace(0, 4*np.pi, num_points)
z = np.linspace(-2, 2, num_points)
r = z**2 + 1

x = r*np.cos(theta)
y = r*np.sin(theta)

spiral_points = np.vstack((x, y, z)).T
spiral_points -= np.mean(spiral_points, axis=0)

df_spiral = pd.DataFrame(spiral_points, columns=["x", "y", "z"])

cmap = sns.diverging_palette(240, 10, as_cmap=True, center="dark")
norm = mcolors.TwoSlopeNorm(vmin=z.min(), vcenter=0, vmax=z.max())

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(x, y, z, c=z, cmap=cmap, norm=norm,
                s=30, alpha=0.8)
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")
plt.savefig("p4_3d.pdf", format="pdf", bbox_inches="tight")

plt.figure(figsize=(4,4))
sns.scatterplot(x=x, y=y, hue=z, palette=cmap, hue_norm=norm, s=40, alpha=1, edgecolor="none")
plt.savefig("p4_2d.pdf", format="pdf", bbox_inches="tight")

"""### Realizando Kernel-PCA"""

sigmas = [1]
ncomp = 0

for sigma in sigmas:
    kpca = KernelPCA(n_components=3, kernel="rbf", gamma=1/sigma).fit(spiral_points)
    kpca_data = kpca.transform(spiral_points)
    plt.figure(figsize=(6,4))
    sns.scatterplot(x = kpca_data[:,0], y = kpca_data[:,1], hue = z, palette=cmap, hue_norm=norm,
                edgecolor="none", s=35, alpha=1)
    plt.legend("")
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.savefig(f"p4_sigma{sigma}.pdf", format="pdf", bbox_inches="tight")

"""### Aplicando K-Means a datos transformados e iniciales."""

k_medias = KMeans(n_clusters=2, random_state=42)

"""#### Datos iniciales."""

inicial_kmedias = k_medias.fit(spiral_points[:,:3])
df_spiral["inicial_labels"] = inicial_kmedias.labels_
centroides = inicial_kmedias.cluster_centers_

plt.figure(figsize=(4,4))
g1 = sns.scatterplot(data = df_spiral,x = "x", y = "y", hue = "inicial_labels",
                edgecolor="none", s=35)
sns.move_legend(g1, loc = "upper right", title = "Clases", labels=["Centro","Extremo"])
plt.xlabel("Y")
plt.ylabel("X")
plt.savefig(f"p4_inicialKmeans2D.pdf", format="pdf", bbox_inches="tight")

palette = sns.color_palette("tab10", n_colors=len(df_spiral["inicial_labels"].unique()))
colors = [palette[label] for label in df_spiral["inicial_labels"]]

fig = plt.figure(figsize=(4, 4))
ax = fig.add_subplot(111, projection="3d")
ax.scatter(x, y, z, c=colors, s=30, alpha=0.8)
plt.savefig("p4_inicialKmeans3D.pdf", format="pdf", bbox_inches="tight")

"""#### Datos transformados."""

kpca_kmedias = k_medias.fit(kpca_data[:,:2])
df_spiral["kpca_labels"] = kpca_kmedias.labels_
centroides = kpca_kmedias.cluster_centers_

plt.figure(figsize=(4,4))
g1 = sns.scatterplot(data = df_spiral,x = "x", y = "y", hue = "kpca_labels",
                edgecolor="none", s=35)
sns.move_legend(g1, loc = "upper right", title = "Clases", labels=["Centro","Extremo"])
plt.xlabel("Y")
plt.ylabel("X")
plt.savefig(f"p4_kpcaKmeans2D.pdf", format="pdf", bbox_inches="tight")

palette = sns.color_palette("tab10", n_colors=len(df_spiral["kpca_labels"].unique()))
colors = [palette[label] for label in df_spiral["kpca_labels"]]

fig = plt.figure(figsize=(4, 4))
ax = fig.add_subplot(111, projection="3d")
ax.scatter(x, y, z, c=colors, s=30, alpha=0.8)
plt.savefig("p4_kpcaKmeans3D.pdf", format="pdf", bbox_inches="tight")

"""## Problema 5"""

num_samples = 1000
factor = 0.3
noise = 0.05

X_circles, y_circles = make_circles(n_samples=num_samples,
                                    factor=factor,
                                    noise=noise)
y_circles = y_circles + 2*(X_circles[:, 0] > 0)

X_circles = (X_circles - np.mean(X_circles,axis=0))/np.std(X_circles, axis=0)

plt.figure(figsize=(5,5))
sns.scatterplot(x=X_circles[:, 0], y=X_circles[:, 1], hue=y_circles,
                palette="tab10", s=20)
plt.savefig("p5_dataset.pdf", format="pdf", bbox_inches="tight")

"""### Aplicando KPCA y PCA"""

def plot_2d(data, x, y, hue, filename):
    plt.figure(figsize=(4,4))
    g1 = sns.scatterplot(data = data,x = x, y = y, hue = hue,
                    edgecolor="none", s=35)
    sns.move_legend(g1, loc = "upper right", title = "Clases")
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.savefig(filename, format="pdf", bbox_inches="tight")

"""#### PCA"""

pca = PCA(n_components=2)
pca_X = pca.fit_transform(X_circles)
pca_data = pd.DataFrame(pca_X, columns=["x","y"])
pca_data["labels"] = y_circles

plot_2d(pca_data,"x","y","labels","p5_pca.pdf")

"""#### KPCA Lineal"""

kpca_lineal = KernelPCA(n_components=2, kernel="linear")
kpca_lineal_X = kpca_lineal.fit_transform(X_circles)

kpca_lineal_data = pd.DataFrame(kpca_lineal_X, columns=["x","y"])
kpca_lineal_data["labels"] = y_circles

plot_2d(kpca_lineal_data, "x", "y","labels", "p5_kpca_lineal.pdf")

"""#### KPCA rbf"""

sigmas = [1.5]

for sigma in sigmas:
    kpca_gauss = KernelPCA(n_components=2, kernel="rbf", gamma=1/sigma)
    kpca_gauss_X = kpca_gauss.fit_transform(X_circles)
    kpca_gauss_data = pd.DataFrame(kpca_gauss_X, columns=["x","y"])
    kpca_gauss_data["labels"] = y_circles

    plot_2d(kpca_gauss_data, "x", "y", "labels", "p5_kpca_gauss.pdf")

"""#### KPCA Polinomial grado 2"""

coefs = [1.5]

for coef in coefs:
    kpca_poly2 = KernelPCA(n_components=2, kernel="poly", degree=2, gamma=coef)
    kpca_poly2_X = kpca_poly2.fit_transform(X_circles)
    kpca_poly2_data = pd.DataFrame(kpca_poly2_X, columns=["x","y"])
    kpca_poly2_data["labels"] = y_circles

    plot_2d(kpca_poly2_data, "x", "y", "labels", "p5_kpca_poly2.pdf")

"""#### KPCA Polinomial grado 3"""

kpca_poly3 = KernelPCA(n_components=2, kernel="poly", degree=3, gamma=0.5, coef0=0.5)
kpca_poly3_X = kpca_poly3.fit_transform(X_circles)
kpca_poly3_data = pd.DataFrame(kpca_poly3_X, columns=["x","y"])
kpca_poly3_data["labels"] = y_circles

plot_2d(kpca_poly3_data, "x", "y", "labels", "p5_kpca_poly3.pdf")